arb-dir: assets/l10n
output-dir: lib/l10n/gen
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
preferred-supported-locales: [en]
output-class: L10n
synthetic-package: false
nullable-getter: false
